apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: 2020-06-29T23:47:51Z
  creationTimestamp: null
  labels:
    app: sonarqube
  name: sonarqube
  namespace: sonarqube
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: The SonarQube Docker image
      tags: sonarqube
    from:
      kind: DockerImage
      name: openshiftdemos/sonarqube:6.7
    importPolicy: {}
    name: "6.7"
    referencePolicy:
      type: Source
status:
  dockerImageRepository: 172.30.1.1:5000/sonarqube
